Update jenkinsfile2

diff --git a/jenkins/jenkinsfile2 b/jenkins/jenkinsfile2
--- a/jenkins/jenkinsfile2
+++ b/jenkins/jenkinsfile2
@@ -70,10 +70,51 @@ pipeline {
                    aws sts get-caller-identity
                    cd $WORKSPACE/handsonlab/terraform
                    /usr/bin/terraform/terraform --version
+                   cd $WORKSPACE/handsonlab/terraform
                    /usr/bin/terraform/terraform init
                 '''
             }
         }
-    }    
+    } 
+    stage('Terraform  Plan') {
+        steps {
+        withCredentials([[
+            $class: 'AmazonWebServicesCredentialsBinding',
+            credentialsId: 'fd4fa4b1-1e70-43de-b796-e13753ecd881',
+            accessKeyVariable: 'AWS_ACCESS_KEY_ID',
+            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
+        ]])
+            {
+                sh '''
+                   env | sort -u
+                   aws sts get-caller-identity
+                   cd $WORKSPACE/handsonlab/terraform
+                   /usr/bin/terraform/terraform plan -detailed-exicode
+                   echo \$? > status
+                '''
+                    def exitCode = readFile('status').trim()
+                def apply = false
+                echo "Terraform Plan Exit Code: ${exitCode}"
+                if (exitCode == "0") {
+                  currentBuild.result = 'SUCCESS'
+                }
+                if (exitCode == "1") {
+                  echo "Plan Failed: ${env.JOB_NAME} - ${env.BUILD_NUMBER} ()"
+                  currentBuild.result = 'FAILURE'
+               }
+               if (exitCode == "2") {
+                 echo "Plan Awaiting Approval: ${env.JOB_NAME} - ${env.BUILD_NUMBER} ()"
+                 try {
+                    input message: 'Apply Plan?', ok: 'Apply'
+                    apply = true
+                   } catch (err) {
+                    echo "Plan Discarded: ${env.JOB_NAME} - ${env.BUILD_NUMBER} ()"
+                    apply = false
+                    currentBuild.result = 'UNSTABLE'
+                }
+            }
+            }
+        }
+    }       
   }
 }
